package jooyung.com.balance_api.auth.dto

data class DeviceInformationDto (
    val deviceId: String,
    val deviceType: String, // PC, Mobile, Tablet, ...
    val os: String, // Windows, macOS, Android, Linux, iOS, iPadOS, ...
    val platform: String, // Web, App, ...
)